Repository Plan-B-PO/docs, pull requests merged in 2019-11, with the labels that each got.

#20 Resolves #17 | Computations id parameter
  api/api.yml
Labels: bug

#21 UC7/8/9 tests
  test_scenarios/UC7_create_new_CN.md
  test_scenarios/UC8_Show owned CN list.md
  test_scenarios/UC9_signal_own_status.md
  test_scenarios/data/UC8_in.puml
  test_scenarios/data/UC8_in.svg
  test_scenarios/data/UC9_in.puml
  test_scenarios/data/UC9_in.svg
Labels: documentation

#18 Add T3
  test_scenarios/T3_Create_New_CT.md
  test_scenarios/UC6_Create CT.md
  test_scenarios/data/T3_in.puml
  test_scenarios/data/T3_in.svg
  test_scenarios/data/T3_out_1.puml
  test_scenarios/data/T3_out_1.svg
  test_scenarios/data/T3_out_2.puml
  test_scenarios/data/T3_out_2.svg
Labels: documentation

#19 Add T4 and T5
  test_scenarios/T4_Activate_CT.md
  test_scenarios/T5_Abort_CT.md
  test_scenarios/UC3_Abort CT.md
  test_scenarios/UC4_Activate Computation Task.md
  test_scenarios/data/T4_in.puml
  test_scenarios/data/T4_in.svg
  test_scenarios/data/T5_in.puml
  test_scenarios/data/T5_in.svg
Labels: documentation

#22 Change response of POST /machine-manager/launcher/computations
  api/api.yml
Labels: documentation

#23 Add IMachines
  api/inner_inerfaces.puml
  api/inner_inerfaces.svg
  components/components.puml
  components/components.svg
Labels: documentation, help wanted

#24 Change T1 to match actual app
  test_scenarios/UC8_Show owned CN list.md
  test_scenarios/data/UC8_in.puml
  test_scenarios/data/UC8_in.svg
Labels: documentation, help wanted

#29 T8
  test_scenarios/T8_Show_Computation_Task_Details.md
Labels: test

#27 New Iteration 2 api features
  api/api.yml
Labels: API

#30 Add initial T9
  test_scenarios/T9_Submit_A_CN.md
Labels: test

#31 Add initial T10
  test_scenarios/T10_Show_Owned_CN_Details.md
Labels: test
